version: '3'

# docker-compose -f test.yml up
services:
  db:
    container_name: my-mysql
    image: mysql:8
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
