version: '3'

# my test
# docker-compose up -f
# 守护开启
# docker-compose up -d
services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      # 站点目录必须为空，否则需配置 EXTRA_ARGS='strapi develop'
      # - EXTRA_ARGS='strapi new'  # 默认 strapi new
    ports:
      - 1337:1337
    volumes:
      - ~/docker/strapi/backend:/srv/app
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes:
      - ~/docker/strapi/mysql:/var/lib/mysql
