version: '3'    # 定义版本，不指定默认为版本 1，新版本功能更多
services:       # 容器
  gitlab:
    image: 'gitlab/gitlab-ce'       # 镜像
    container_name: gitlab          # 容器名称
    privileged: true                # 解决权限问题
    # restart: always                 # 同 --restart 参数
    ports:                          # 端口映射，同 -p 参数，本地端口:容器端口
      - '443:443'
      - '222:22'
      - '8091:8080'
    volumes:                        # 数据卷,本地文件夹:容器文件夹
      - '~/docker/gitlab/config:/etc/gitlab'
      - '~/docker/gitlab/logs:/var/log/gitlab'
      - '~/docker/gitlab/data:/var/opt/gitlab'
